
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev", "main" ]


jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: tar the folder
      uses: a7ul/tar-action@v1.1.0
      id: compress
      with:
        command: c
        cwd: .
        files: .
        outPath: loveapp.tar.gz
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
          name: loveletterwriter
          path: ./loveapp.tar.gz
  use:
    runs-on: self-hosted
    needs: build
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: loveletterwriter
          path: .
      - name: Extract files
        uses: a7ul/tar-action@v1.1.0
        id: extract
        with:
          command: x
          cwd: /var/www/loveletterwriter
          files: loveapp.tar.gz
  
